/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package gr.parisk85.mappers

import gr.parisk85.mappers.function.FunctionBestCustomerGateway
import gr.parisk85.mappers.function.FunctionBuyerToCustomerMapper

class FunctionBuyerToCustomerMapperTest extends BestCustomerGatewayBaseTest {

    def mapper = FunctionBuyerToCustomerMapper.newInstance()

    @Override
    def sut() {
        return FunctionBestCustomerGateway.newInstance(restClient, mapper)
    }
}
