/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package gr.parisk85.mappers

import gr.parisk85.mappers.generated.GeneratedBestCustomerGateway
import gr.parisk85.mappers.generated.GeneratedBuyerToCustomerMapper
import org.mapstruct.factory.Mappers

class GeneratedBuyerToCustomerMapperTest extends BestCustomerGatewayBaseTest {

    def mapper = Mappers.getMapper(GeneratedBuyerToCustomerMapper)

    @Override
    def sut() {
        return GeneratedBestCustomerGateway.newInstance(restClient, mapper)
    }
}
