/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package gr.parisk85.mappers

import gr.parisk85.mappers.staticmapper.StaticBestCustomerGateway

class StaticBuyerToCustomerMapperTest extends BestCustomerGatewayBaseTest {

    @Override
    def sut() {
        return StaticBestCustomerGateway.newInstance(restClient)
    }
}
